### PR TITLE
Pull from upstream

### PR DESCRIPTION
**Pull request by dgonyeo**
I just did a pull from upstream. No merge conflicts. Probably has the pony fix thing. Someone else is welcome to check.

cc @liam-middlebrook @eatnumber1

### CODE REVIEW

**Comment by dgonyeo** [comment]
Interesting that this only has commits through 6/6/2016 though...

**Comment by eatnumber1** [comment]
Feel free to merge without review once Travis is done.

**Comment by eatnumber1** [comment]
Is 6/6/16 the last commit? I wouldn't be surprised if NH4 development has died down since the NH devs came back to life.

**Comment by dgonyeo** [comment]
Yeah that's the last commit I see in their git

**Comment by eatnumber1** [comment]
Probably worth emailing the nh4 devs to ask what their plans are...

**Comment by liam-middlebrook** [comment]
I was just on the IRC yesterday they're still actively developing it.
I also think we should be working off of their git repository on nethack4.org, not this third-party fork.

**Comment by liam-middlebrook** [comment]
Maybe I'm just being pedantic, but there was a *much* cleaner Git history on the official repo that I pulled in from: https://github.com/ComputerScienceHouse/bingehack4/compare/master...liam-middlebrook:upstream-master?expand=1

**Comment by dgonyeo** [comment]
From IRC:
> the lead developer got busy with work, and then he got recruited to the 3.x Dev Team

> So yes, NH4 development has slowed down considerably

**Pull request merged**
